### PR TITLE
Always close connection when end consumption

### PR DESCRIPTION
**Pull request by tmuehl**
In case of another exception than a IOException, the connection wasn't closed and potentially left stalled.

@jhorstmann @AdnanKukuljac

### CODE REVIEW

**Comment by jhorstmann** [comment]
@tmuehl Do you have the stacktrace from where this exception originated? I'm trying to reproduce this in a unit test.

**Comment by tmuehl** [comment]
@jhorstmann If a `RuntimeException` is thrown in the listener, this message is propagated up without closing the http connection. Therefore, you might end up with stalled connections.

```
public class ConnectionClosingTest {
    
    @Test
    public void nakadiReaderClosesConnection() throws Exception {
        final PoolingHttpClientConnectionManager connManager = new PoolingHttpClientConnectionManager();
        connManager.setMaxTotal(3);
        connManager.setDefaultMaxPerRoute(3);

        final CloseableHttpClient httpClient = HttpClientBuilder.create()
                .setConnectionManager(connManager)
                .useSystemProperties().build();

        final HttpComponentsClientHttpRequestFactory requestFactory = new HttpComponentsClientHttpRequestFactory(httpClient);

        final NakadiClient nakadiClient = new NakadiClientBuilder(new URI("https://nakadi.example.com"))
                .withClientHttpRequestFactory(requestFactory).build();
        
        while (true) {
            nakadiClient.stream("foobar").listen(Foobar.class, events -> {
                throw new RuntimeException("Intentionally thrown.");
            });
        }
    }
    
    private static class Foobar {
        private int id;
        private String text;
    }
}
```

After reconnecting 3 times, you can run out of connections.
Do you have a better proposal?

**Comment by jhorstmann** [comment]
Got it, I had an error in my test setup, but I'll try to fix this in a slightly different way. Thanks a lot for the report!

**Comment by tmuehl** [comment]
@jhorstmann Great, thanks for fixing it! Closed this in favour of #155

**Pull request closed without merging**
