### PR TITLE
Fix Jackson Deprecation Warning

### PR DESCRIPTION
**Pull request by lukasniemeier-zalando**
Fixing the blocking issue here.

### CODE REVIEW

**Comment by jhorstmann** [comment]
I actually left the deprecated name on purpose because apart from that constant the library should still be compatible with jackson 2.6, but since we are not testing that version we might as well remove compatibility.

**Comment by lukasniemeier-zalando** [comment]
If you want to signal compatibility with 2.6 then I'd propose to change the dependency to `2.6.7` and stick with the old name (but I'm in for going with `2.7.5` :wink:).

**Comment by jhorstmann** [comment]
Deprecation warning was fixed in #41 by using `SNAKE_CASE`, if someone needs jackson 2.6 compatibility there should be a new issue for it.

**Comment by lukasniemeier-zalando** [comment]
But now the `README` is not in sync anymore. Nooooooooooooooooooooooooooooooooooo :boom:

**Pull request closed without merging**
